environment: development
log_level: info

# API Gateway Configuration
api_gateway:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  webhook_registry_addr: "webhook-registry:8086"
  observability_addr: "observability:8085"
  grpc_timeout: 10s
  cors_enabled: true
  cors_allowed_origins: ["*"]
  cors_allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  cors_allowed_headers: ["Content-Type", "Authorization"]

# Webhook Registry Configuration
webhook_registry:
  port: 8086
  host: "0.0.0.0"
  cache_enabled: true
  cache_ttl: 300s

# Event Ingestion Configuration
event_ingestion:
  port: 8082
  host: "0.0.0.0"
  rate_limit_enabled: true
  rate_limit_rps: 1000
  kafka:
    client_id: "event-ingestion"
    compression_type: "gzip"
    batch_size: 1000
    linger_ms: 10
    retry_backoff_ms: 100
    max_retries: 3
    request_timeout_ms: 30000
    message_timeout_ms: 300000
    acks: "all"
    enable_idempotence: true
    events_topic: "webhook-events"
    dlq_topic: "webhook-events-dlq"

# Webhook Dispatcher Configuration
dispatcher:
  webhook_registry_addr: "webhook-registry:8086"
  retry_manager_addr: "retry-manager:8084"
  observability_addr: "observability:8085"
  grpc_timeout: 10s
  http_timeout: 30s
  http_max_retries: 3
  http_retry_delay: 1s
  http_max_conns_per_host: 10
  http_max_idle_conns: 100
  worker_count: 10
  batch_size: 100
  process_interval: 1s
  kafka:
    group_id: "webhook-dispatcher"
    client_id: "webhook-dispatcher"
    auto_offset_reset: "earliest"
    enable_auto_commit: true
    session_timeout_ms: 30000
    heartbeat_interval_ms: 3000
    fetch_min_bytes: 1
    events_topic: "webhook-events"

# Retry Manager Configuration
retry_manager:
  port: 8084
  host: "0.0.0.0"
  max_retries: 5
  initial_delay: 1s
  max_delay: 300s
  backoff_multiplier: 2.0
  jitter_enabled: true
  process_interval: 10s
  batch_size: 100
  worker_count: 5
  redis:
    address: redis:6379
    password: redis123
    db: 0
    max_retries: 3
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    pool_size: 10
    min_idle_conns: 5
    max_idle_conns: 10
    conn_max_lifetime: 3600s
    conn_max_idle_time: 300s

# Observability Configuration
observability:
  port: 8085
  host: "0.0.0.0"
  log_retention_days: 30
  log_level: info

# Dead Letter Queue Configuration
dlq:
  port: 8087
  host: "0.0.0.0"
  topic: "webhook-dlq"

# Database Configuration
database:
  host: postgres
  port: 5432
  database: webhook_db
  username: postgres
  password: postgres123
  ssl_mode: disable
  max_conns: 25
  min_conns: 5
  max_life: 3600s
  max_idle: 1800s

# Redis Configuration
redis:
  address: redis:6379
  password: redis123
  db: 0
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_size: 10
  min_idle_conns: 5
  max_idle_conns: 10
  conn_max_lifetime: 3600s
  conn_max_idle_time: 300s

# Kafka Configuration
kafka:
  brokers: ["kafka-kraft:29092"]
  security_protocol: ""
  sasl_mechanism: ""
  sasl_username: ""
  sasl_password: ""

# Metrics Configuration
metrics:
  enabled: true
  listen_addr: "0.0.0.0:9090"
  path: "/metrics"
  namespace: "webhook"
  subsystem: "service"

# Schema Registry Configuration
schema_registry:
  port: 8088
  url: "http://schema-registry-service:8088"
  username: ""
  password: ""

# Security Configuration
security:
  oauth2_enabled: false
  oauth2_issuer: ""
  oauth2_client_id: ""
  oauth2_client_secret: ""
  jwt_secret: "${JWT_SECRET:-generate-secure-secret-in-production}"
  jwt_expiration: 3600s
  jwt_issuer: "webhook-service"
  jwt_audience: "webhook-api"
  hmac_secret: "${HMAC_SECRET:-generate-secure-hmac-secret-in-production}"
  tls_enabled: false
  tls_cert_file: ""
  tls_key_file: ""
  rate_limit_enabled: true
  rate_limit_rps: 100
  rate_limit_burst: 200 